### ISSUE TITLE
Dynamo is not supported on Python 3.12+

### ISSUE THREAD

**Issue by treya-lin** [kyutai-labs/moshi#156]
### Backend impacted

The PyTorch implementation

### Operating system

Linux

### Hardware

GPU with CUDA

### Description

I installed the environment with python 3.12 as it was recommended in the doc, but when I tried to run the server, it returned such error saying that Dynamo not supported on Python 3.12+. So why was this version recommended? I will attach the error message, my command and my env setup below.

### Extra information

env:
```
conda create -n env_moshi python=3.12
conda activate env_moshi
# I downloaded these prebuilt torch wheels to speed up installing.
python -m pip install torch-2.3.1+cu121-cp312-cp312-linux_x86_64.whl       torchvision-0.18.1+cu121-cp312-cp312-linux_x86_64.whl
torchaudio-2.3.1+cu121-cp312-cp312-linux_x86_64.whl
python -m pip install moshi
```

run moshi server (I donwloaded the models in local dir)
```
MOSHI_RES_DIR=/home/resources/models/kyutai/moshika-pytorch-bf16/;  python -m moshi.server --host 0.0.0.0 --port 8898 --tokenizer $MOSHI_RES_DIR/tokenizer_spm_32k_3.model --moshi-weight $MOSHI_RES_DIR/model.safetensors --mimi-weight $MOSHI_RES_DIR/tokenizer-e351c8d8-checkpoint125.safetensors
```

log and error:
```
[Info] loading mimi
[Info] mimi loaded
[Info] loading moshi
[Info] moshi loaded
[Info] warming up the model
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/user/anaconda3/envs/env_moshi/lib/python3.12/site-packages/moshi/server.py", line 256, in <module>
    main()
  File "/home/user/anaconda3/envs/env_moshi/lib/python3.12/site-packages/moshi/server.py", line 222, in main
    state.warmup()
  File "/home/user/anaconda3/envs/env_moshi/lib/python3.12/site-packages/moshi/server.py", line 67, in warmup
    codes = self.mimi.encode(chunk)
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/env_moshi/lib/python3.12/site-packages/moshi/models/compression.py", line 378, in encode
    emb = self._encode_to_unquantized_latent(x)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/env_moshi/lib/python3.12/site-packages/moshi/models/compression.py", line 364, in _encode_to_unquantized_latent
    (emb,) = state.graphed_tr_enc(emb)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/env_moshi/lib/python3.12/site-packages/moshi/utils/compile.py", line 271, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/env_moshi/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/env_moshi/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/env_moshi/lib/python3.12/site-packages/moshi/modules/transformer.py", line 743, in forward
    z = self.transformer(x, *args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/env_moshi/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/env_moshi/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/env_moshi/lib/python3.12/site-packages/moshi/modules/transformer.py", line 692, in forward
    x = layer(x, *args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/env_moshi/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/env_moshi/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/env_moshi/lib/python3.12/site-packages/moshi/modules/transformer.py", line 587, in forward
    x = self._sa_block(x)
        ^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/env_moshi/lib/python3.12/site-packages/moshi/modules/transformer.py", line 580, in _sa_block
    update = self.self_attn(x, x, x)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/env_moshi/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/env_moshi/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/env_moshi/lib/python3.12/site-packages/moshi/modules/transformer.py", line 399, in forward
    q, k = self.rope(q, k, offset, time_before_heads=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/env_moshi/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/env_moshi/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/env_moshi/lib/python3.12/site-packages/moshi/modules/rope.py", line 90, in forward
    return apply_rope(q, k, offset, self.max_period, time_before_heads)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/env_moshi/lib/python3.12/site-packages/moshi/utils/compile.py", line 51, in _wrapped
    fun_compiled = torch.compile(fun)
                   ^^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/env_moshi/lib/python3.12/site-packages/torch/__init__.py", line 1868, in compile
    raise RuntimeError("Dynamo is not supported on Python 3.12+")
```

### Environment

Fill in the following information on your system.
- Operating system version:

If the backend impacted is PyTorch:
- Python version: 3.12
- PyTorch version: 2.3.1+cu121
- CUDA version (run `python -c 'import torch;  print(torch.version.cuda)'`): 12.1
- GPU model and memory: 3090Ti, 24G
  
If the backend is MLX:
- Mac model:

**Comment by LaurentMazare** [comment]
This doesn't seem to be moshi specific but rather than when using pytorch 2.3 and python 3.12, torch compile does not work, see https://github.com/pytorch/pytorch/issues/120233
Maybe you could try updating pytorch to at least 2.4 ? (or try with python 3.11)

**Comment by treya-lin** [comment]
Thanks. I switched to torch241-cu121-py311 and it is working now.
